/* Write your T-SQL query statement below */
SELECT ACTIVITY_DATE AS DAY , COUNT(DISTINCT USER_ID) AS ACTIVE_USERS FROM ACTIVITY 
WHERE ACTIVITY_DATE <= '2019-07-27' AND DATEDIFF(DAY , ACTIVITY_DATE , '2019-07-27')<30
GROUP BY ACTIVITY_DATE;